name: Build and Test

on:
  push:
    branches:
      - main
      - dev
      - ci

jobs:
  integration:
    name: Build Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - sample-app
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - run: |
          chmod -R +x ./scripts
          docker build -t task-builder .
          pushd examples
            for d in */ ; do
              if [ -d "$d" ]; then
                pushd $d
                echo "$d"
                docker run \
                  -e BUILDER_WORKBENCH=/app/task \
                  -v "/var/run/docker.sock":"/var/run/docker.sock" \
                  -v `pwd`:/app/task \
                  -i task-builder \
                  arg0 .
                  # clean up
                  sudo rm -rf dist
                popd
              fi
            done
          popd

      - name: Setup build tools
        id: build-actions
        uses: ./ # Uses an action
        with:
          arg0: 'arg0'
          directory: ./examples/${{ matrix.app }}
