name: Build and Test

on:
  push:
    branches:
      - main
      - dev
      - ci

jobs:
  integration:
    name: Build Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - sample-app
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - run: |
          chmod -R +x ./scripts
          docker build -t task-builder .
          for d in examples/ ; do
              pushd $d
              echo "$d"
              docker run -v `pwd`:/src -it task-builder arg0 arg1
              popd
          done

      - name: Setup build tools
        id: build-actions
        uses: ./ # Uses an action
        with:
          directory: examples/${{ matrix.app }}
          arg0: 'Mona the Octocat'