name: Build and Test

on:
  push:
    branches:
      - main
      - dev
      - ci

jobs:
  integration:
    name: Build Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - sample-app
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - run: |
          docker build -t task-builder .
          chmod -R +x ./scripts
      - name: Setup build tools
        id: build-actions
        uses: ./ # Uses an action
        with:
          directory: examples/${{ matrix.app }}
          arg0: 'Mona the Octocat'