name: Build and Test

on:
  push:
    branches:
      - main
      - dev
      - ci

jobs:
  integration:
    name: Build Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - sample-app
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - run: |
          chmod -R +x ./scripts
          docker build -t task-builder .
          pushd examples
            for d in */ ; do
              if [ -d "$d" ]; then
                pushd $d
                echo "$d"
                docker run -e BUILDER_WORKBENCH=/app/task -v `pwd`:/app/task -i task-builder arg0 .
                popd
              fi
            done
          popd

      - name: Setup build tools
        id: build-actions
        uses: ./ # Uses an action
        with:
          directory: examples/${{ matrix.app }}
          arg0: 'Mona the Octocat'