name: Build and Test

on:
  push:
    branches:
      - main
      - dev
      - ci

jobs:
  integration:
    name: Build Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup build tools
        id: build-actions
        uses: ./ # Uses an action
        with:
          arg0: 'Mona the Octocat'