name: Build and Test

on:
  push:
    branches:
      - main
      - dev
      - ci

jobs:
  integration:
    name: Build Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - run: |
          docker pull docker.pkg.github.com/laraboot-io/task-build-action/task-build-action:latest
      - name: Setup build tools
        id: build-actionsg
        uses: ./ # Uses an action
        with:
          arg0: 'Mona the Octocat'