name: Build and Test

on:
  push:
    branches:
      - docker

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          docker build -t task-builder .
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish Image
        uses: craftech-io/package-action@v3.1.0
        id: url-GPR
        with:
          tags: latest
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: output
        run: echo ${{ steps.url-GPR.outputs.imageURL }}